# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f2a4fde50f1c664cf378ef6b24c64f6e62e075045bd04403e457be41e321d1ee936682eeb0db348556b845e9c6af0bb5b2eedc93f3273826543fdc0e8fbd601

test:
  secret_key_base: 05cdad34a090052e857f4303dd8cafdd2ad169779d54af445319eed3c2b4ec6f9b688120abcdda257835cda4106339bb4d5b1ecfb6acd9cd1f24f80c5cf1a6ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
